### ISSUE TITLE
The MongoDB was stopped after installed the images

### ISSUE THREAD

**Issue by bjlvfei** [bitnami/bitnami-docker-mongodb#230]
Hi Team,

I have meet an issue when the pods were created in k8s cluster

kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
mongo-mongodb-arbiter-0     1/1     Running   5          21m
mongo-mongodb-primary-0     1/1     Running   0          21m
mongo-mongodb-secondary-0   1/1     Running   0          21m

kubectl logs -f mongo-mongodb-arbiter-0
 23:08:36.71 
 23:08:36.71 Welcome to the Bitnami mongodb container
 23:08:36.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
 23:08:36.72 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
 23:08:36.72 Send us your feedback at containers@bitnami.com
 23:08:36.72 
 23:08:36.72 INFO  ==> ** Starting MongoDB setup **
 23:08:36.74 INFO  ==> Validating settings in MONGODB_* env vars...
 23:08:36.82 INFO  ==> Initializing MongoDB...
 23:08:36.83 INFO  ==> No injected configuration files found. Creating default config files...
 23:08:36.87 INFO  ==> Deploying MongoDB from scratch...
 23:08:37.96 INFO  ==> Creating users...
 23:08:37.97 INFO  ==> Users created
 23:08:37.97 INFO  ==> Writing keyfile for replica set authentication...
 23:08:38.01 INFO  ==> Configuring MongoDB replica set...
 23:08:38.02 INFO  ==> Stopping MongoDB...
 23:08:40.67 INFO  ==> Trying to connect to MongoDB server mongo-mongodb...
 23:08:40.69 INFO  ==> Found MongoDB server listening at mongo-mongodb:27017 !
 23:11:45.91 ERROR ==> Node mongo-mongodb did not become available
 23:11:45.93 INFO  ==> Stopping MongoDB...

that why the mongodb client can not connect to mongodb server. Any idea? Thanks!
kubectl run --namespace graylog mongo-mongodb-client --rm --tty -i --restart='Never' --image docker.io/bitnami/mongodb:4.2.4-debian-10-r0 --command -- mongo admin --host mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD
MongoDB shell version v4.2.4
connecting to: mongodb://mongo-mongodb:27017/admin?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
2020-08-28T23:09:14.437+0000 E  QUERY    [js] Error: Authentication failed. :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2020-08-28T23:09:14.439+0000 F  -        [main] exception: connect failed
2020-08-28T23:09:14.439+0000 E  -        [main] exiting with code 1
pod "mongo-mongodb-client" deleted
pod graylog/mongo-mongodb-client terminated (Error)

Levi
Thanks!

**Comment by bjlvfei** [comment]
Hi Team,

I have saw the pod graylog where show the error as below. Maybe it's give us some clue about it.

com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='root', source='admin', password=<hidden>, mechanismProperties={}}
        at com.mongodb.connection.SaslAuthenticator.wrapException(SaslAuthenticator.java:162) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.access$200(SaslAuthenticator.java:39) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:68) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.doAsSubject(SaslAuthenticator.java:168) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.authenticate(SaslAuthenticator.java:46) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultAuthenticator.authenticate(DefaultAuthenticator.java:32) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:122) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:52) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:127) ~[graylog.jar:?]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:114) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server mongo-mongodb.graylog.svc.cluster.local:27017. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed", "operationTime" : { "$timestamp" : { "t" : 1598705985, "i" : 1 } }, "$clusterTime" : { "clusterTime" : { "$timestamp" : { "t" : 1598705985, "i" : 1 } }, "signature" : { "hash" : { "$binary" : "EY+xk2dligXYwCw78/LnXNJRJq4=", "$type" : "00" }, "keyId" : { "$numberLong" : "6851006718734761986" } } } }
        at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:164) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:295) ~[graylog.jar:?]
        at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255) ~[graylog.jar:?]
        at com.mongodb.connection.CommandHelper.sendAndReceive(CommandHelper.java:84) ~[graylog.jar:?]
        at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:34) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.sendSaslContinue(SaslAuthenticator.java:123) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator.access$100(SaslAuthenticator.java:39) ~[graylog.jar:?]
        at com.mongodb.connection.SaslAuthenticator$1.run(SaslAuthenticator.java:65) ~[graylog.jar:?]
        ... 9 more


Levi
Thanks!

**Comment by joancafom** [comment]
HI @bjlvfei 

I would like to know a little bit more about this. Are you using our [MongoDB Helm Chart](https://github.com/bitnami/charts/tree/master/bitnami/mongodb)? If so, could you please provide me with the custom values you are using to deploy it?

I have tried creating a new release with the Bitnami MongoDB Chart and all seems to be in order 😁:

```console
$ helm install gamma --set architecture=replicaset bitnami/mongodb 
NAME: gamma
LAST DEPLOYED: Mon Aug 31 09:33:14 2020
NAMESPACE: default
STATUS: deployed
...

$  kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
gamma-mongodb-0           1/1     Running   0          5m55s
gamma-mongodb-1           1/1     Running   0          3m15s
gamma-mongodb-arbiter-0   1/1     Running   0          5m55s
```

Also, from your first [comment](https://github.com/bitnami/bitnami-docker-mongodb/issues/230#issue-688405043) it might be that you are using an old version of the Bitnami MongoDB Chart. I might be wrong, but can you verify this?

Thanks!

**Comment by bjlvfei** [comment]
Hi @joancafom 

I'm already found the root cause which need to delete the old pvc in namespace.  The pods were running now using the helm chart as below.

helm install mongo ./mongodb --namespace graylog

root@mongo-mongodb graylog]# kubectl get pods | grep mongo
mongo-mongodb-arbiter-0                    1/1     Running    0          30m
mongo-mongodb-primary-0                    1/1     Running    0          30m
mongo-mongodb-secondary-0                  1/1     Running    0          30m

[root@mongo-mongodb graylog]# kubectl run --namespace graylog mongo-mongodb-client --rm --tty -i --restart='Never' --image bitnami/mongodb --command -- mongo admin --host mongo-mongodb --authenticationDatabase admin -u root -p $MONGODB_ROOT_PASSWORD

If you don't see a command prompt, try pressing enter.
             
rs0:PRIMARY> 
rs0:PRIMARY> show dbs;
admin   0.000GB
config  0.000GB
local   0.000GB


Levi
Thanks!
