### ISSUE TITLE
[helm/mongodb] Using NFS as PV for mongodb authentication is lost

### ISSUE THREAD

**Issue by eldada** [bitnami/bitnami-docker-mongodb#94]
**Description**
When deploying MongoDB helm chart to GKE cluster and using an existing NFS based PVC, the user is reported to be created, but in fact, it's not.

**Steps to reproduce the issue:**
1. Create NFS server
2. Create NFS PV and PVC
3. Deploy MongoDB chart with 
```
...
--set persistence.enabled=true \
--set persistence.existingClaim=nfs-pvc \
--set mongodbRootPassword=password \
--set mongodbUsername=dist \
--set mongodbPassword: password \
--set mongodbDatabase: bt \
...
```
4. Get into pod
```
$ kubectl exec -it mongo-pod bash
```
5. Try opening shell 
```
$ mongo -u dist -p password bt
```

**Describe the results you received:**
Error opening shell (authentication failed)

**Describe the results you expected:**
Shell opened to requested user and db properly

**Additional information you deem important (e.g. issue happens only occasionally):**
When using default storage class PVC (gdisk), no errors.

**NOTE**
On boot log, I see:
```
nami    INFO  Initializing mongodb
mongodb INFO  ==&gt; Creating root user...
mongodb INFO  ==&gt; Creating dist user...
mongodb INFO  ==&gt; Enabling authentication...
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Root Password: **********
mongodb INFO     Username: dist
mongodb INFO     Password: **********
mongodb INFO     Database: bt
mongodb INFO   (Passwords are not shown for security reasons)
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
```
When deleting pod and allowing restart on the **BAD** env, I see:
```
nami    INFO  Initializing mongodb
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
```
When deleting pod and allowing restart on the **GOOD** env, I see same log as the initial one.

**Version**
Chart: 2.0.2
MongoDB docker: 3.6.3
K8s: GKE (K8s) 1.9.6

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
GKE K8s cluster

**Comment by juan131** [comment]
Hi @eldada 

Could you share the PV/PVC definitions you're using (YAML or JSON format)? I'd like to reproduce the issue using the same persistence configuration.

**Comment by eldada** [comment]
I was able to reproduce with a `hostPath` PV on Minikube.
The PV/PVC Yaml is:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

I created `/data/mongodb` (in minikube) and set its permissions to 777.

I deployed the helm chart with `--set persistence.existingClaim=mongodb-pvc`.

Allowed it to finish starting up.

I deleted the pod with `kubectl delete pod <pod>`.

It starts up with the bad log 
```
nami    INFO  Initializing mongodb
mongodb INFO 
mongodb INFO  ########################################################################
mongodb INFO   Installation parameters for mongodb:
mongodb INFO     Persisted data and properties have been restored.
mongodb INFO     Any input specified will not take effect.
mongodb INFO   This installation requires no credentials.
mongodb INFO  ########################################################################
mongodb INFO 
nami    INFO  mongodb successfully initialized
```

NOTE - I did see the `conf` and `data` directories created in `/data/mongodb` in minikube.

**Comment by juan131** [comment]
I was able to reproduce it! The log message is wrong despite the configuration file is persisted and authentication is enabled. 

Instead of showing:

```
mongodb INFO   This installation requires no credentials.
```

The logic should be able to detect whether `authorization` is enabled or not and adapt the message.

**Comment by eldada** [comment]
In my case, the admin user that was created in the first boot is unavailable after the restart. Can you check this? A simple `mongo -u admin -p password db` passed on first run and  failed after the restart.

**Comment by juan131** [comment]
Hi @eldada 

Could you try using the command below?

```
mongo admin -u root -p $MONGODB_ROOT_PASSWORD
```

Please note that the env. variables should be the same ones after restarting so you can access to `MONGODB_ROOT_PASSWORD` for instance.

**Comment by allen-servedio** [comment]
@juan131 - in case this is related, we have seen possibly related issues when trying to use Kubeapps with NFS: https://github.com/kubeapps/kubeapps/issues/118 and possibly a hint here: https://github.com/kubeapps/kubeapps/issues/92#issuecomment-351444121

**Comment by juan131** [comment]
Hi @allen-servedio I decided to open an internal task so we can investigate possible issues with NFS and the Bitnami images persistence. Thanks for reporting it. We will update this thread as soon as we have more news.

**Comment by eldada** [comment]
@juan131 - I tried 
```
mongo admin -u root -p $MONGODB_ROOT_PASSWORD
``` 
as you suggested before and after. Both **worked**!

Another thing I noticed, running with `hostPath` PV and PVC is that permissions to the `conf` and `data` directories differ (looking from within the `minikube` VM):
```
$ ls -la /data/xray/mongodb/
total 16
drwxrwxrwx 4 root   root   4096 May 13 10:18 .
drwxrwxrwx 4 root   root   4096 May  7 12:33 ..
-rw-r--r-- 1 root   root      0 May 13 10:18 .initialized
drwxr-xr-x 2 root   root   4096 May 13 10:18 conf
drwxr-xr-x 3 docker docker 4096 May 13 10:18 data
```
This might also lead to unexpected behaviour.

**Comment by zucher** [comment]
Hi,

I'm starting monocular into the IBM Container service context, and the mongodb pods restart indefinitely.

I don't know if this issue is associated with but I got the following traces:
```
Welcome to the Bitnami mongodb container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing mongodb
Error executing 'postInstallation': Group '4294967294' not found
```

```
Back-off restarting failed container
(combined from similar events): Readiness probe failed: MongoDB shell version v3.4.9 connecting to: mongodb://127.0.0.1:27017 2018-06-03T08:11:40.271+0000 W NETWORK [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused 2018-06-03T08:11:40.279+0000 E QUERY [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed : connect@src/mongo/shell/mongo.js:237:13 @(connect):1:6 exception: connect failed
```

```json
{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "intentional-lambkin-mongodb-5d5f879684-d8lk5",
    "generateName": "intentional-lambkin-mongodb-5d5f879684-",
    "namespace": "default",
    "selfLink": "/api/v1/namespaces/default/pods/intentional-lambkin-mongodb-5d5f879684-d8lk5",
    "uid": "ea98c281-667d-11e8-b89b-9e16dda73907",
    "resourceVersion": "1752136",
    "creationTimestamp": "2018-06-02T15:59:22Z",
    "labels": {
      "app": "intentional-lambkin-mongodb",
      "pod-template-hash": "1819435240"
    },
    "ownerReferences": [
      {
        "apiVersion": "extensions/v1beta1",
        "kind": "ReplicaSet",
        "name": "intentional-lambkin-mongodb-5d5f879684",
        "uid": "ea9837fd-667d-11e8-b89b-9e16dda73907",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ]
  },
  "spec": {
    "volumes": [
      {
        "name": "data",
        "persistentVolumeClaim": {
          "claimName": "intentional-lambkin-mongodb"
        }
      },
      {
        "name": "default-token-2hkf6",
        "secret": {
          "secretName": "default-token-2hkf6",
          "defaultMode": 420
        }
      }
    ],
    "containers": [
      {
        "name": "intentional-lambkin-mongodb",
        "image": "bitnami/mongodb:3.4.9-r1",
        "ports": [
          {
            "name": "mongodb",
            "containerPort": 27017,
            "protocol": "TCP"
          }
        ],
        "env": [
          {
            "name": "MONGODB_ROOT_PASSWORD",
            "valueFrom": {
              "secretKeyRef": {
                "name": "intentional-lambkin-mongodb",
                "key": "mongodb-root-password"
              }
            }
          },
          {
            "name": "MONGODB_USERNAME"
          },
          {
            "name": "MONGODB_PASSWORD",
            "valueFrom": {
              "secretKeyRef": {
                "name": "intentional-lambkin-mongodb",
                "key": "mongodb-password"
              }
            }
          },
          {
            "name": "MONGODB_DATABASE"
          }
        ],
        "resources": {
          "requests": {
            "cpu": "100m",
            "memory": "256Mi"
          }
        },
        "volumeMounts": [
          {
            "name": "data",
            "mountPath": "/bitnami/mongodb"
          },
          {
            "name": "default-token-2hkf6",
            "readOnly": true,
            "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
          }
        ],
        "livenessProbe": {
          "exec": {
            "command": [
              "mongo",
              "--eval",
              "db.adminCommand('ping')"
            ]
          },
          "initialDelaySeconds": 30,
          "timeoutSeconds": 5,
          "periodSeconds": 10,
          "successThreshold": 1,
          "failureThreshold": 3
        },
        "readinessProbe": {
          "exec": {
            "command": [
              "mongo",
              "--eval",
              "db.adminCommand('ping')"
            ]
          },
          "initialDelaySeconds": 5,
          "timeoutSeconds": 1,
          "periodSeconds": 10,
          "successThreshold": 1,
          "failureThreshold": 3
        },
        "terminationMessagePath": "/dev/termination-log",
        "terminationMessagePolicy": "File",
        "imagePullPolicy": "IfNotPresent"
      }
    ],
    "restartPolicy": "Always",
    "terminationGracePeriodSeconds": 30,
    "dnsPolicy": "ClusterFirst",
    "serviceAccountName": "default",
    "serviceAccount": "default",
    "nodeName": "10.135.242.145",
    "securityContext": {},
    "imagePullSecrets": [
      {
        "name": "bluemix-default-secret"
      },
      {
        "name": "bluemix-default-secret-regional"
      },
      {
        "name": "bluemix-default-secret-international"
      },
      {
        "name": "draft-pullsecret"
      }
    ],
    "schedulerName": "default-scheduler",
    "tolerations": [
      {
        "key": "node.kubernetes.io/not-ready",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      },
      {
        "key": "node.kubernetes.io/unreachable",
        "operator": "Exists",
        "effect": "NoExecute",
        "tolerationSeconds": 300
      }
    ]
  },
  "status": {
    "phase": "Running",
    "conditions": [
      {
        "type": "Initialized",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-06-02T16:01:32Z"
      },
      {
        "type": "Ready",
        "status": "False",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-06-02T16:01:32Z",
        "reason": "ContainersNotReady",
        "message": "containers with unready status: [intentional-lambkin-mongodb]"
      },
      {
        "type": "PodScheduled",
        "status": "True",
        "lastProbeTime": null,
        "lastTransitionTime": "2018-06-02T16:01:32Z"
      }
    ],
    "hostIP": "X.X.X.X",
    "podIP": "172.30.43.146",
    "startTime": "2018-06-02T16:01:32Z",
    "containerStatuses": [
      {
        "name": "intentional-lambkin-mongodb",
        "state": {
          "waiting": {
            "reason": "CrashLoopBackOff",
            "message": "Back-off 5m0s restarting failed container=intentional-lambkin-mongodb pod=intentional-lambkin-mongodb-5d5f879684-d8lk5_default(ea98c281-667d-11e8-b89b-9e16dda73907)"
          }
        },
        "lastState": {
          "terminated": {
            "exitCode": 1,
            "reason": "Error",
            "startedAt": "2018-06-03T08:49:39Z",
            "finishedAt": "2018-06-03T08:50:04Z",
            "containerID": "docker://92b07058eba9d319e1c770a13ae63c010a35dad592f1c015670d2de72e52da13"
          }
        },
        "ready": false,
        "restartCount": 187,
        "image": "bitnami/mongodb:3.4.9-r1",
        "imageID": "docker-pullable://bitnami/mongodb@sha256:8e44ca67b03e2b67cd76db9e85a57bba89212a92e75f473e5eebdcff833b58d3",
        "containerID": "docker://92b07058eba9d319e1c770a13ae63c010a35dad592f1c015670d2de72e52da13"
      }
    ],
    "qosClass": "Burstable"
  }
}
```

**Comment by juan131** [comment]
Hi @zucher 

It think this is a different issue. The MongoDB image is trying to create an user and group to the system (mongo:mongo) and it was unable to do it.

You installed MongoDB using the [MongoDB chart](https://github.com/kubernetes/charts/tree/master/stable/mongodb), didn't you? 

@tompizmor do you have any hint why this could be happening?

**Comment by zucher** [comment]
Hi @juan131, 

I just request a kubeapps up or an helm install monocular/monocular on our IBM Container Service.

**Comment by tompizmor** [comment]
@zucher, I would try to deploy the mongodb image passing the `NAMI_LOG_LEVEL=trace8` environment variable. That will give us more information about the exact point of failure.

Per the error I am just guessing that IBM Container Service runs the container with a random non-root user like Openshift does, and that is making the mongodb container to fail.
> Error executing 'postInstallation': Group '4294967294' not found

**Comment by zucher** [comment]
My logs:

```
2018-06-04T19:29:25.783508684Z 
2018-06-04T19:29:25.783553825Z Welcome to the Bitnami mongodb container
2018-06-04T19:29:25.783560405Z Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb
2018-06-04T19:29:25.783566161Z Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues
2018-06-04T19:29:25.783570883Z Send us your feedback at containers@bitnami.com
2018-06-04T19:29:25.783575327Z 
2018-06-04T19:29:29.392575397Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.398338244Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.399706058Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.400705875Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.401525336Z mongodb TRACE [normalize] File normalization: lib -&gt; /opt/bitnami/mongodb/lib
2018-06-04T19:29:29.403954799Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.40608015Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.407022034Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.407855122Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.408692707Z mongodb TRACE [normalize] File normalization: lib -&gt; /opt/bitnami/mongodb/lib
2018-06-04T19:29:29.438745575Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.443835337Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.444986191Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.445944402Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.446780144Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.44751559Z mongodb TRACE [normalize] File normalization: lib -&gt; /opt/bitnami/mongodb/lib
2018-06-04T19:29:29.4532258Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.454064858Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.455517938Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.457032057Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.458046861Z mongodb TRACE [normalize] File normalization: lib -&gt; /opt/bitnami/mongodb/lib
2018-06-04T19:29:29.459845082Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.460645397Z mongodb TRACE [normalize] File normalization: bin -&gt; /opt/bitnami/mongodb/bin
2018-06-04T19:29:29.46190547Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.462785569Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.463506711Z mongodb TRACE [normalize] File normalization: lib -&gt; /opt/bitnami/mongodb/lib
2018-06-04T19:29:29.468201622Z nami    INFO  Initializing mongodb
2018-06-04T19:29:29.513955846Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.577520105Z mongodb TRACE [normalize] File normalization: tmp -&gt; /opt/bitnami/mongodb/tmp
...
2018-06-04T19:29:29.577520105Z mongodb TRACE [normalize] File normalization: tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.578707789Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.581554965Z mongodb TRACE [mkdir] File normalization: /opt/bitnami/mongodb/tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.597284925Z mongodb TRACE [mkdir] File normalization: /opt/bitnami/mongodb/logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.597310455Z mongodb TRACE [exists] File normalization: /bitnami/mongodb/.initialized -&gt; /bitnami/mongodb/.initialized
2018-06-04T19:29:29.606281679Z mongodb TRACE [exists] File normalization: /opt/bitnami/mongodb/conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.606302349Z mongodb TRACE [isLink] File normalization: /opt/bitnami/mongodb/conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.606307803Z mongodb TRACE [restorePersistedData] Restoring /bitnami/mongodb/conf to /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.606312385Z mongodb TRACE [delete] File normalization: /opt/bitnami/mongodb/conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.609472761Z mongodb TRACE [exists] File normalization: /opt/bitnami/mongodb/data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.633779697Z mongodb TRACE [isLink] File normalization: /opt/bitnami/mongodb/data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.63442283Z mongodb TRACE [restorePersistedData] Restoring /bitnami/mongodb/data to /opt/bitnami/mongodb/data
2018-06-04T19:29:29.634812108Z mongodb TRACE [delete] File normalization: /opt/bitnami/mongodb/data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.63747776Z mongodb TRACE [touch] File normalization: /bitnami/mongodb/.restored -&gt; /bitnami/mongodb/.restored
2018-06-04T19:29:29.643341534Z mongodb TRACE [normalize] File normalization: tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.64435608Z mongodb TRACE [normalize] File normalization: logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.648613518Z mongodb TRACE [isLink] File normalization: /opt/bitnami/mongodb/tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.649591019Z mongodb TRACE [isDirectory] File normalization: /opt/bitnami/mongodb/tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.650646778Z mongodb TRACE [configurePermissions] File to chown: /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.651097834Z mongodb TRACE [chown] File normalization: /opt/bitnami/mongodb/tmp -&gt; /opt/bitnami/mongodb/tmp
2018-06-04T19:29:29.656962684Z mongodb TRACE [isLink] File normalization: /opt/bitnami/mongodb/logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.657413353Z mongodb TRACE [isDirectory] File normalization: /opt/bitnami/mongodb/logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.657868267Z mongodb TRACE [configurePermissions] File to chown: /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.658268031Z mongodb TRACE [chown] File normalization: /opt/bitnami/mongodb/logs -&gt; /opt/bitnami/mongodb/logs
2018-06-04T19:29:29.660729466Z mongodb TRACE [normalize] File normalization: conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.662091796Z mongodb TRACE [normalize] File normalization: data -&gt; /opt/bitnami/mongodb/data
2018-06-04T19:29:29.66578939Z mongodb TRACE [isLink] File normalization: /opt/bitnami/mongodb/conf -&gt; /opt/bitnami/mongodb/conf
2018-06-04T19:29:29.666383042Z mongodb TRACE [isDirectory] File normalization: /bitnami/mongodb/conf -&gt; /bitnami/mongodb/conf
2018-06-04T19:29:29.66822222Z mongodb TRACE [configurePermissions] File to chown: /bitnami/mongodb/conf
...
mongodb TRACE [retry] Error: Error: Group '4294967294' not found
mongodb TRACE [retry] Trying to configure permissions... 0 remaining attempts
Error executing 'postInstallation': Group '4294967294' not found
nami    TRACE Error: Error executing 'postInstallation': Group '4294967294' not found
    at _findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:10:11)
    at findGroup (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/find-group.js:37:10)
    at getGid (/opt/bitnami/nami/node_modules/nami-utils/lib/os/user-management/get-gid.js:22:25)
    at _chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:22:33)
    at /opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:77:7
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.&lt;anonymous&gt; (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at Object.chown (/opt/bitnami/nami/node_modules/nami-utils/lib/file/chown.js:76:7)
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
    at _configurePermissions (/root/.nami/components/com.bitnami.mongodb/lib/component.js:137:13)
```

**Comment by juan131** [comment]
Hi @zucher 

Per your logs, it seems you're using an old version of MongoDB container. I recommend you to edit the "imagePullPolicy" on the MongoDB deployment and use "latest" to update it.

Regarding the error, I'm not familiar with that platform (IBM Container Services) but I agree with @tompizmor. We found some issues on other container platforms with "root" containers such as MongoDB. That's why we started migrating some containers to "non-root" configurations such as MariadDB or NGINX.

Could you please contact the IBM support team and ask them if there are any kind of limitation when using containers that run as user "root"?

**Comment by sameersbn** [comment]
@zucher Looks like there is some filesystem level permissions issue with using mongodb and NFS volumes. It would be great if we could debug and fix it if possible.

Re: getting `kubeapps up` working, the good thing is that the mongodb container in the kubeapps setup does not require a persistent volume as mongodb is used primarily as a cache. The kubeapps master also removes this requirement and uses a ephemeral volume for mongodb data. You could try the following command to setup kubeapps:

```
./kubeapps up --dry-run | \
  sed -e 's|persistentVolumeClaim:|emptyDir: {}|' \
      -e 's|          claimName: mongodb-data||' \
  kubectl apply -f -
```

**Comment by zucher** [comment]
Thank you @sameersbn , with your command, in the mean time, until issue fix, we can progress in our study.

**Comment by prydonius** [comment]
I believe I'm seeing the same issue as originally described in my docker for mac k8s environment. MongoDB seems to crash at some point on startup, and after restarting authentication is not enabled. This means I can connect to MongoDB without authenticating and I'm able to write to the db.

If I install the MongoDB chart with `persistence.enabled=false` the container never restarts and authentication is enabled. If I try to connect to MongoDB and perform an action, it fails as expected:

```
> show databases;
2018-09-12T22:16:10.133+0000 E QUERY    [js] Error: listDatabases failed:{
	"ok" : 0,
	"errmsg" : "command listDatabases requires authentication",
	"code" : 13,
	"codeName" : "Unauthorized"
} :****
```

My guess is that something is going wrong in that initial startup, and when MongoDB restarts and recovers from the persistence it doesn't have authentication setup correctly and therefore becomes unauthenticated. This seems like a pretty serious bug as people may unknowingly be running MongoDB without authentication.

**Comment by tompizmor** [comment]
Thanks, @prydonius!! I will try to prioritize investigating this issue.

**Comment by carrodher** [comment]
We did a big refactor of the MongoDB image some months ago trying to fix different reported issues, please feel free to reopen this one if the issue persists.
